
--View Name -> PEDW.PNR_PASSENGER View
CREATE OR REPLACE VIEW TERADATA_MIG.PEDW.PNR_PASSENGER(
	PNR_LOC,	
	PNR_CRT_DTE,	
	PNR_PSGR_NUM,	
	PSGR_TYPE_CDE,	
	PSGR_LAST_NAME,	
	PSGR_FIRST_NAME,
	PSGR_TITLE,	PSGR_PRB_GENDER_CDE,	
	PSGR_CHILD_IND,	PSGR_INFANT_IND,	
	PNR_GRP_IND,	PNR_GRP_CNT,
	FQTV_CARRIER_CDE,	
	FQTV_NUM,	
	FQTV_TIER_CDE,	
	FQTV_SRC_CDE,	
	POSTDATE,	
	UCI
) as   

SELECT PNR_LOC, 
PNR_CRT_DTE, 
PNR_PSGR_NUM, 
PSGR_TYPE_CDE, 
PSGR_LAST_NAME, 
PSGR_FIRST_NAME, 
PSGR_TITLE, 
psgr_prb_gender_cde, 
psgr_child_ind, psgr_infant_ind, 
PNR_GRP_IND, NULL AS PNR_GRP_CNT, FQTV_CARRIER_CDE, 
FQTV_NUM, FQTV_TIER_CDE, FQTV_SRC_CDE, POSTDATE, UCI  
FROM  pedw_db.pnr_passenger;

--View Name -> PEDW.REF_PNR_SEGMENT View
CREATE OR REPLACE VIEW TERADATA_MIG.PEDW.PNR_SEGMENT(
	PNR_LOC,	PNR_CRT_DTE,SEQNO,	PNR_REQTYP_CDE,	PNR_SEG_NUM,	PNR_SEG_ARUNK_IND,	PNR_SEG_TRANS_CDE,	PNR_SEG_STATUS_CDE,	PNR_SEG_ISTATUS_CDE,	CARRIER_CDE,	FLIGHT_NUM,	SEG_SCHD_ORIG,	SEG_SCHD_DEP_LCL_DTE,
	SEG_SCHD_DEP_LCL_TME,	SEG_SCHD_DEST,	SEG_SCHD_ARR_LCL_DTE,	SEG_SCHD_ARR_LCL_TME,	PNR_SEG_OD_CONN_NUM,	PNR_SEG_STATS_CDE,
	PNR_SEG_PSGR_CNT,	PNR_SEG_BKG_CLS_CDE,	PNR_SEG_SUB_CLS_CDE,	CDSHR_CARRIER_CDE,	CDSHR_FLIGHT_NUM,	CDSHR_BOOK_CLS_CDE,
	OPER_CARRIER_CDE,	OPER_FLIGHT_NUM,	PNR_SEG_CDSHR_CRC,	PNR_SEG_REV_CDSHR_IND,	PNR_SEG_CDSHR_IND,	PNR_SEG_OD_FARE_AMT,	PNR_SEG_REV_LOSS_AMT,	PNR_SEG_BID_AMT,	PNR_SEG_NEW_IND,	PNR_SEG_ACT_IND,	PNR_SEG_AGT_SINE_IND,
	PNR_SEG_RDU_IND,	PNR_SEG_STS_CHG_IND,	PNR_SEG_CNL_IND,	PNR_SEG_FST_IND,	PNR_SEG_BRD_CNTL_IND,	PNR_SEG_NON_WAIT_IND,
	PNR_SEG_INBND_CONN_IND,	PNR_SEG_OUTBND_CONN_IND,	PNR_SEG_INOUT_CHG_IND,	PNR_SEG_TIMING_IND,
	PNR_SEG_ASC_IND,	PNR_SEG_SPC_SLD_IND,	PNR_SEG_INV_NOT_DTL_IND,	PNR_SEG_CTYPE_IND,	PNR_SEG_OVRBOOK_IND,
	PNR_SEG_NO_STOPOVR_IND,	PNR_SEG_NON_STOP_IND,	PNR_SEG_ENTER_72_IND,	PNR_SEG_DUP_IND,	PNR_SEG_ASC_MSG_IND,
	PNR_SEG_OVR_SLS_IND,	PNR_SEG_WIODAT1_IND,	PNR_SEG_MARR_IND,	PNR_SEG_GTEE_SLS_IND,	PNR_SEG_BKL_SPC_CDSHR_IND,
	PNR_SEG_MARR_RMVD_IND,	PNR_SEG_OVERSALE_IND,	PNR_SEG_PSH_OVERSALE_IND,	PNR_SEG_YIELD_IND,	PNR_SEG_SEG_REACCOM_IND,	PNR_SEG_FLIGHT_STERILE_IND,	PNR_SEG_BKD_REACOMM_IND,	PNR_SEG_CONN_FLIGHT_IND,
	PNR_SEG_STAT_CHNGD_IND,	PNR_SEG_SEG_OPTION,	PNR_SEG_INV_IDX_DTE,	PNR_ACT_SEG_NUM,	POSTDATE
) as 

SELECT PNR_LOC, PNR_CRT_DTE, SEQNO, PNR_REQTYP_CDE, PNR_SEG_NUM, PNR_SEG_ARUNK_IND, PNR_SEG_TRANS_CDE, PNR_SEG_STATUS_CDE, PNR_SEG_ISTATUS_CDE, CARRIER_CDE, FLIGHT_NUM, SEG_SCHD_DEP_ORIG AS SEG_SCHD_ORIG, SEG_SCHD_DEP_LCL_DTE, SEG_SCHD_DEP_LCL_TME, SEG_SCHD_DEP_DEST AS SEG_SCHD_DEST, SEG_SCHD_ARR_LCL_DTE, SEG_SCHD_ARR_LCL_TME, PNR_SEG_OD_CONN_NUM, PNR_SEG_STATS_CDE, PNR_SEG_PSGR_CNT, PNR_SEG_BKG_CLS_CDE, PNR_SEG_SUB_CLS_CDE, CDSHR_CARRIER_CDE, CDSHR_FLIGHT_NUM, CDSHR_BOOK_CLS_CDE, OPER_CARRIER_CDE, OPER_FLIGHT_NUM, PNR_SEG_CDSHR_CRC, PNR_SEG_REV_CDSHR_IND, PNR_SEG_CDSHR_IND, PNR_SEG_OD_FARE_AMT, PNR_SEG_REV_LOSS_AMT, PNR_SEG_BID_AMT, PNR_SEG_NEW_IND, PNR_SEG_ACT_IND, PNR_SEG_AGT_SINE_IND, PNR_SEG_RDU_IND, PNR_SEG_STS_CHG_IND, PNR_SEG_CNL_IND, PNR_SEG_FST_IND, PNR_SEG_BRD_CNTL_IND, PNR_SEG_NON_WAIT_IND, PNR_SEG_INBND_CONN_IND, PNR_SEG_OUTBND_CONN_IND, PNR_SEG_INOUT_CHG_IND, PNR_SEG_TIMING_IND, PNR_SEG_ASC_IND, PNR_SEG_SPC_SLD_IND, PNR_SEG_INV_NOT_DTL_IND, PNR_SEG_CTYPE_IND, PNR_SEG_OVRBOOK_IND, PNR_SEG_NO_STOPOVR_IND, PNR_SEG_NON_STOP_IND, PNR_SEG_ENTER_72_IND, PNR_SEG_DUP_IND, PNR_SEG_ASC_MSG_IND, PNR_SEG_OVR_SLS_IND, PNR_SEG_WIODAT1_IND, PNR_SEG_MARR_IND, PNR_SEG_GTEE_SLS_IND, PNR_SEG_BKL_SPC_CDSHR_IND, PNR_SEG_MARR_RMVD_IND, PNR_SEG_OVERSALE_IND, PNR_SEG_PSH_OVERSALE_IND, PNR_SEG_YIELD_IND, PNR_SEG_SEG_REACCOM_IND, PNR_SEG_FLIGHT_STERILE_IND, PNR_SEG_BKD_REACOMM_IND, PNR_SEG_CONN_FLIGHT_IND, PNR_SEG_STAT_CHNGD_IND, PNR_SEG_SEG_OPTION, PNR_SEG_INV_IDX_DTE, PNR_ACT_SEG_NUM, POSTDATE 
FROM pedw_db.pnr_segment;

--View Name -> PEDW.REF_PNR_SEG_STATUS View
CREATE OR REPLACE VIEW TERADATA_MIG.PEDW.REF_PNR_SEG_STATUS(
	PNR_SEG_STATUS_CDE,
	PNR_SEG_STATUS_DESC,
	PNR_ACTIVE_SEG_IND,
	POSTDATE
) as 
SELECT PNR_SEG_STATUS_CDE, 
PNR_SEG_STATUS_DESC, 
PNR_ACTIVE_SEG_IND, 
POSTDATE 
FROM pedw_db.REF_PNR_SEG_STATUS;



