
--View Name -> BAGGAGE_EVENT_BPM View
CREATE OR REPLACE VIEW TERADATA_MIG.PEDW.BAGGAGE_EVENT_BPM(
	LEG_ID,	
	TAG_NUM,	
	FULL_TAG_NUM,	
	INSE_DTE,	
	INSE_TME,	
	MSG_SRCE_CDE,	
	MSG_TYP_CDE,	
	PNR_LOC,
	PSGR_SURNM,	
	PSGR_TIL_NME,	
	PSGR_SEAT_NUM,	
	PSGR_STS,	
	PSGR_CLS_CDE,	
	BAG_SEQ_NUM,	
	BAG_SCTY_NUM,	
	FRQ_TRAVL_NUM,	
	CARRIER_CDE,	
	FLIGHT_NUM,	
	FLIGHT_ORIG_DTE,	
	LEG_ORIG,
	LEG_DEST,	
	CNX_IN_CARRIER_CDE,	
	CNX_IN_FLIGHT_NUM,	
	CNX_IN_FLIGHT_ORIG_DTE,	
	CNX_IN_LEG_ORIG,
	CNX_IN_LEG_DEST,	
	CNX_OUT_CARRIER_CDE,	
	CNX_OUT_FLIGHT_NUM,	
	CNX_OUT_FLIGHT_ORIG_DTE,
	CNX_OUT_LEG_ORIG,	
	CNX_OUT_LEG_DEST,	
	VER,	
	SEC_CDE,	
	CHKIN_AGT_ID,	
	SCANNER_ID,	
	TRAN_LCL_DTE,
	TRAN_LCL_TME,	
	TRAN_LCL_TMS,	
	TRAN_GMT_DTE,	
	TRAN_GMT_TME,	
	TRAN_GMT_TMS,	
	READ_LOC,
	SENT_LOC,	
	LD_DATA,	
	TAG_STS,	
	LD_SEQ_NUM,	
	AUTH_LD_FL,	
	EXCPT_TYP,	
	BAG_IND,	
	BAG_CNT,
	BAG_WGHT,	
	INTRNL_CARRIER_DATA_1,	
	INTRNL_CARRIER_DATA_2,	
	INTRNL_CARRIER_DATA_3,	
	ID,
	BAG_STS_CDE
) as 
SELECT FLT.LEG_ID, 
BPM.TAG_NUM, 
BPM.FULL_TAG_NUM, 
BPM.INSE_DTE, 
BPM.INSE_TME, MSG_SRCE_CDE, 
FLT.MSG_TYP_CDE, 
PNR_LOC, 
PD.PSGR_SURNM AS PSGR_SURNM, 
PSGR_GVN_NME AS PSGR_TIL_NME, FLT.
PSGR_SEAT_NUM AS PSGR_SEAT_NUM, 
PD.PSGR_STS AS PSGR_STS, 
PD.PSGR_CLS_CDE AS PSGR_CLS_CDE, 
PD.BAG_SEQ_NUM, 
PD.BAG_SCTY_NUM, 
PD.FRQ_TRAVL_NUM, 
FLT.CARRIER_CDE, 
FLT.FLIGHT_NUM, 
FLT.FLIGHT_ORIG_DTE, 
FLT.LEG_ORIG, 
FLT.LEG_DEST, 
FLT.CNX_IN_CARRIER_CDE, 
FLT.CNX_IN_FLIGHT_NUM, 
FLT.CNX_IN_FLIGHT_ORIG_DTE, 
FLT.CNX_IN_LEG_ORIG, 
FLT.CNX_IN_LEG_DEST, 
FLT.CNX_OUT_CARRIER_CDE, 
FLT.CNX_OUT_FLIGHT_NUM, 
FLT.CNX_OUT_FLIGHT_ORIG_DTE, 
FLT.CNX_OUT_LEG_ORIG, 
FLT.CNX_OUT_LEG_DEST, 
FLT.VER, 
SEC_CDE, 
CHKIN_AGT_ID, 
SCANNER_ID, 
TRAN_LCL_DTE, 
TRAN_LCL_TME, 
TRAN_LCL_TMS, 
TRAN_GMT_DTE, 
TRAN_GMT_TME, 
TRAN_GMT_TMS, 
READ_LOC, 
SENT_LOC, 
LD_DATA, 
TAG_STS, 
LD_SEQ_NUM, 
AUTH_LD_FL, 
EXCPT_TYP, 
WT.BAG_IND, 
WT.BAG_CNT, 
WT.BAG_WGHT, 
INTRNL_CARRIER_DATA_1, 
INTRNL_CARRIER_DATA_2, 
INTRNL_CARRIER_DATA_3, 
BPM.ID, 
BPM.BAG_STS_CDE AS BAG_STS_CDE 
FROM PEDW_DB.BAG_TRAN_BPM AS BPM 

LEFT OUTER JOIN PEDW_DB.BAG_LEG_DTL AS FLT 
ON upper(trim(BPM.TAG_NUM)) = upper(trim(FLT.TAG_NUM)) 
  AND BPM.ID = FLT.ID 
  AND BPM.INSE_DTE = FLT.INSE_DTE AND BPM.INSE_TME = FLT.INSE_TME 
  AND upper(trim(FLT.VER)) = upper(trim(BPM.VER)) 
  AND upper(trim(FLT.MSG_TYP_CDE)) = upper(trim('BPM')) 

LEFT OUTER JOIN PEDW_DB.BAG_PSGR_DTL AS PD 
ON upper(trim(BPM.TAG_NUM)) = upper(trim(PD.TAG_NUM)) 
 AND BPM.ID = PD.ID 
 AND BPM.INSE_DTE = PD.INSE_DTE AND BPM.INSE_TME = PD.INSE_TME 

LEFT OUTER JOIN PEDW_DB.BAG_WGHT_DTL AS WT 
ON BPM.ID = WT.ID 
  AND BPM.INSE_DTE = WT.INSE_DTE AND BPM.INSE_TME = WT.INSE_TME 
  AND upper(trim(BPM.TAG_NUM)) = upper(trim(WT.TAG_NUM));

