

CREATE OR REPLACE FUNCTION BI_REPORTSDB_REH.BI_REPORTS_OPS.FN_OPS0055_ACF_ENGINE_CHECK_REPORT("STARTDATE" VARCHAR(16777216), "ENDDATE" VARCHAR(16777216))

RETURNS TABLE 
("Carrier" VARCHAR(16777216), 
"Flight #," NUMBER(38,0), 
"Fleet," VARCHAR(16777216), 
"Orig," VARCHAR(16777216), 
"Actual,Dep Time" TIMESTAMP_NTZ(9), 
"Dest," VARCHAR(16777216), 
"Actual,Arr Time" TIMESTAMP_NTZ(9), 
"Scheduled UTC,Arr Time" TIMESTAMP_NTZ(9), 
"Actual,Arr Interval Hour" NUMBER(38,0), 
"Scheduled UTC,Arr Interval Hour" NUMBER(38,0), 
"Air Time," NUMBER(38,0), 
"Actl,Blk Mins" NUMBER(38,0), 
"Schd,Blk Mins" NUMBER(38,0), 
"Planned ZFW," NUMBER(38,0), 
"Actl ZFW," NUMBER(38,0), 
"Planned,Air Time" NUMBER(38,0), 
"Planned,Touchdown Fuel" NUMBER(38,0), 
"Actual,Touchdown Fuel" NUMBER(38,0), 
"Planned,Block Fuel" NUMBER(38,0), 
"MIN_FUEL" NUMBER(38,0), 
"Alt Station" VARCHAR(16777216), 
"FIT" NUMBER(38,0), 
"Planned,Fuel Burn" NUMBER(38,0), 
"ALT Fuel," NUMBER(38,0), 
"ATC Fuel," NUMBER(38,0), 
"WXX Fuel," NUMBER(38,0), 
"DEV Fuel," NUMBER(38,0), 
"OPN Fuel," NUMBER(38,0), 
"CTG Fuel," NUMBER(38,0), 
"Actl,Fuel Burn" NUMBER(38,0), 
"Actl Fuel Burn,Corrected" NUMBER(38,0), 
"Delta Burn" NUMBER(38,10), 
"Delta Burn %" NUMBER(38,10), 
"Delta Burn %,Normalized" FLOAT, 
"Flight Count" NUMBER(38,0), 
"Weight Prime" NUMBER(17,6), 
"LEG_DIST_AIR_AMT" NUMBER(38,0), 
"TDX Check" NUMBER(38,0), 
"STO Check" NUMBER(38,0), 
"LND Check" NUMBER(38,0), 
"TAR Check" NUMBER(38,0), 
"ZFW Check" NUMBER(38,0), 
"EET Check" NUMBER(38,0), 
"Outlier Check" NUMBER(38,0), 
"Date" DATE)
LANGUAGE SQL
AS 
	SELECT
		CARRIER_CDE AS "Carrier",
		FLIGHT_NUM AS "Flight #,",
		ACFT_SUBTYPE_CDE AS "Fleet,",
		LEG_ACTL_ORIG AS "Orig,",
		LEG_ACTL_DEP_LCL_TMS AS "Actual,Dep Time",		
		LEG_ACTL_DEST AS "Dest,",
		LEG_ACTL_ARR_LCL_TMS AS "Actual,Arr Time",
		LEG_SCHD_ARR_TMS AS "Scheduled UTC,Arr Time",
		ACTL_ARR_INTERVAL_HOUR AS "Actual,Arr Interval Hour",
		SCHD_ARR_INTERVAL_HOUR_UTC AS "Scheduled UTC,Arr Interval Hour",
		ACTL_AIRTIME AS "Air Time,",
		LEG_ACTL_BLK_MINS AS "Actl,Blk Mins",
		LEG_SCHD_BLK_MINS AS "Schd,Blk Mins",
		PLAN_ZEROFUEL_WGHT_AMT AS "Planned ZFW,",
		ZFW_ACUTAL AS "Actl ZFW,",
		PLN_AIR_TIME AS "Planned,Air Time",
		PLN_TDWN_FUEL AS "Planned,Touchdown Fuel",
		FUEL_ONB_LND AS "Actual,Touchdown Fuel",		
		PLN_BLOCK_FUEL AS "Planned,Block Fuel",
		MIN_FUEL AS "MIN_FUEL",
		ALT_STN AS "Alt Station",
		FIT AS "FIT",
		PLN_FUEL_BURN AS "Planned,Fuel Burn",		
		ALT_FUEL AS "ALT Fuel,",
		ATC_FUEL AS "ATC Fuel,",
		WXX_FUEL AS "WXX Fuel,",
		DEV_FUEL AS "DEV Fuel,",
		OPN_FUEL AS "OPN Fuel,",
		CTG_FUEL AS "CTG Fuel,",
		ACTL_FUEL_BURN AS "Actl,Fuel Burn",
		ACTL_FUEL_BURN_CORR AS "Actl Fuel Burn,Corrected",
		DELTA_BURN AS "Delta Burn",
		DELTA_BURN_PCT AS "Delta Burn %",
		DELTA_BURN_PCT_N AS "Delta Burn %,Normalized",
		NUM_FLIGHTS AS "Flight Count",		
		WEIGHT_PRIME AS "Weight Prime",
		LEG_DIST_AIR_AMT AS "LEG_DIST_AIR_AMT",		
		TDX_ONB_CHK AS "TDX Check",
		STO_ONB_CHK AS "STO Check",
		LND_ONB_CHK AS "LND Check",
		TAR_ONB_CHK AS "TAR Check",
		ACT_ZFW_CHK AS "ZFW Check",
		EET_CHK AS "EET Check",
		OUTLIER_CHECK AS "Outlier Check",
		FLIGHT_ORIG_LCL_DTE AS "Date"
	FROM
	(
	SELECT 
		CARRIER_CDE,
		CARRIER_NME,
		IATA_CDE,
		FLIGHT_ORIG_LCL_DTE,
		LEG_SCHD_DEP_TME,
		FLIGHT_NUM,
		FLIGHTS,
		ACFT_SUBTYPE_CDE,
		LEG_SECTOR_CDE,
		LEG_ACTL_ORIG,
		LEG_ACTL_DEP_LCL_TMS,
		LEG_ACTL_DEST,
		LEG_ACTL_ARR_LCL_TMS,
		LEG_SCHD_ARR_LCL_TMS,
		LEG_SCHD_ARR_TMS,
		CITY_PAIR,
		ACTL_AIRTIME,
		LEG_ACTL_BLK_MINS,
		LEG_SCHD_BLK_MINS,
		ACT_DLY_CODE,
		LEG_DEP_DELAY_SECD_CDE,
		COST_INDEX_ECO_CRUISE,
		AVG_WIND_COMP,
		PLAN_ZEROFUEL_WGHT_AMT,
		ZFW_ACUTAL,
		PLN_AIR_TIME,
		PLN_TDWN_FUEL,
		PLN_BLOCK_FUEL,
		MIN_FUEL,
		LEG_TAXI_OUT,
		ALT_FUEL,
		ALT_STN,
		PLN_SDWN_FUEL_AMT,
		FIT,
		PLN_TAXI_OUT_TIME,
		ACTL_TAXI_OUT_TIME,
		PLN_FUEL_BURN,
		FUEL_ONB_DEP,
		FUEL_ONB_STO,
		FUEL_ONB_LND,
		FUEL_ONB_ARR,
		TAXI_OUT_FF,
		TAXI_IN_FF,
		ACTL_TAXI_IN_TIME,
		ACTL_CALC_ONB_ARR,
		PLN_TAXI_IN_TIME,
		PLN_TDWN_FUEL_AUX,
		TKG,
		ATC_FUEL,
		WXX_FUEL,
		DEV_FUEL,
		OPN_FUEL,
		CTG_FUEL,
		DELTA_BURN,
		DELTA_BURN_PCT,
		DELTA_BURN_PCT_N,
		NUM_FLIGHTS,
		LEG_DIST_AIR_AMT,
		ACTL_ARR_INTERVAL_HOUR,
		SCHD_ARR_INTERVAL_HOUR,
		SCHD_ARR_INTERVAL_HOUR_UTC,
		WEIGHT_PRIME
	FROM

	   (SELECT *,
	    CASE WHEN ACFT_SUBTYPE_CDE = ''DH4'' THEN 0.0100
		 WHEN ACFT_SUBTYPE_CDE = ''E75'' THEN 0.0300
		 WHEN ACFT_SUBTYPE_CDE = ''7M8'' THEN 0.0250
		 WHEN ACFT_SUBTYPE_CDE = ''7M9'' THEN 0.0250
		 WHEN ACFT_SUBTYPE_CDE = ''763'' THEN 0.0250
		 WHEN ACFT_SUBTYPE_CDE = ''76F'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''320'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''E90'' THEN 0.0300
		 WHEN ACFT_SUBTYPE_CDE = ''321'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''319'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''333'' THEN 0.0280
		 WHEN ACFT_SUBTYPE_CDE = ''789'' THEN 0.0235
		 WHEN ACFT_SUBTYPE_CDE = ''788'' THEN 0.0235
		 WHEN ACFT_SUBTYPE_CDE = ''77P'' THEN 0.0235
		 WHEN ACFT_SUBTYPE_CDE = ''77L'' THEN 0.0235
		 WHEN ACFT_SUBTYPE_CDE = ''77W'' THEN 0.0235
		 WHEN ACFT_SUBTYPE_CDE = ''76P'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''31L'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''32I'' THEN 0.0275
		 WHEN ACFT_SUBTYPE_CDE = ''223'' THEN 0.0237
		 ELSE 0.0300 
	     END AS ZFW_FACTOR,			
         ACTL_FUEL_BURN - (((FUEL_ONB_STO + ZFW_ACUTAL) - (MIN_FUEL + PLAN_ZEROFUEL_WGHT_AMT)) * ZFW_FACTOR * (ACTL_AIRTIME / 60)) AS   ACTL_FUEL_BURN_CORR_1,
	     (ACTL_FUEL_BURN_CORR_1 - PLN_FUEL_BURN) AS DELTA_BURN,
	    (DELTA_BURN / PLN_FUEL_BURN) * 100 AS DELTA_BURN_PCT,
	    DELTA_BURN_PCT * SQRT((LEG_DIST_AIR_AMT * 1.852) / 1000) AS DELTA_BURN_PCT_N,
	    
		CASE WHEN (FUEL_ONB_DEP >= ((MIN_FUEL + LEG_TAXI_OUT) * 0.8) 
		AND FUEL_ONB_DEP <= ((MIN_FUEL + LEG_TAXI_OUT) * 1.2)) THEN 1 ELSE 0 
		END AS TDX_ONB_CHK,
	    
		CASE WHEN (FUEL_ONB_STO >= (MIN_FUEL * 0.8)  
		AND FUEL_ONB_STO <= (MIN_FUEL * 1.2)) THEN 1 ELSE 0 
		END AS STO_ONB_CHK,
	    
		CASE WHEN (FUEL_ONB_LND >= (PLN_SDWN_FUEL_AMT * 0.7) 
		AND FUEL_ONB_LND <= (PLN_SDWN_FUEL_AMT * 1.3)) THEN 1 ELSE 0 
		END AS LND_ONB_CHK,
	    
		CASE WHEN (FUEL_ONB_ARR >= ((PLN_SDWN_FUEL_AMT - (ACTL_TAXI_IN_TIME * TAXI_IN_FF)) * 0.7)
		AND FUEL_ONB_ARR <= ((PLN_SDWN_FUEL_AMT - (ACTL_TAXI_IN_TIME * TAXI_IN_FF)) * 1.3)) THEN 1 ELSE 0 
		END AS TAR_ONB_CHK,
        
		CASE WHEN  (ZFW_ACUTAL >= (PLAN_ZEROFUEL_WGHT_AMT * 0.9) 
		AND ZFW_ACUTAL <= (PLAN_ZEROFUEL_WGHT_AMT * 1.1)) THEN 1 ELSE 0 
		END AS ACT_ZFW_CHK,
	    
		CASE WHEN  (PLN_AIR_TIME <> NULL) THEN 1 ELSE 0 
		END AS EET_CHK,
	    
		CASE WHEN  ((TDX_ONB_CHK = 1) AND (STO_ONB_CHK = 1) AND (LND_ONB_CHK = 1) AND (TAR_ONB_CHK = 1) 
		AND (ACT_ZFW_CHK = 1) AND (EET_CHK = 1)) THEN 1 ELSE 0 
		END AS OUTLIER_CHECK,
	    CARRIER_CDE || CITY_PAIR || ACFT_SUBTYPE_CDE AS JOIN_KEY
	FROM
				

(SELECT
     F.CARRIER_CDE,	F.FLIGHT_NUM,	F.FLIGHT_SUFFIX_CDE,	F.FLIGHT_ORIG_DTE,	F.FLIGHT_LEG_NUM,	F.ACFT_SUBTYPE_CDE,	F.ACFT_REGS_CDE,	F.LEG_ID,	F.LEG_SCHD_ORIG,	F.LEG_SCHD_DEP_DTE,	F.LEG_SCHD_DEP_TME,	F.LEG_SCHD_DEST,
	F.LEG_SCHD_ARR_DTE,	F.LEG_SCHD_ARR_TME,	F.LEG_SECTOR_CDE,	F.LEG_ACTL_ORIG,	F.LEG_ACTL_DEP_DTE,
	F.LEG_ACTL_DEP_TME,	F.LEG_ACTL_DEP_TMS,	F.LEG_ACTL_DEST,	F.LEG_ACTL_ARR_DTE,	F.LEG_ACTL_ARR_TME,
	F.LEG_ACTL_ARR_TMS,	F.LEG_AIRBORNE_DTE,	F.LEG_AIRBORNE_TME,	F.LEG_AIRBORNE_TMS,	F.LEG_LANDING_DTE,
	F.LEG_LANDING_TME,	F.LEG_LANDING_TMS,	F.ACTL_AIRTIME,	F.LEG_ACTL_BLK_MINS,	F.LEG_SCHD_BLK_MINS,
	F.LDO_OFFSET,	F.FLIGHT_ORIG_LCL_DTE,	F.LEG_SCHD_DEP_LCL_TMS,	F.LEG_SCHD_DEP_LCL_DTE,
	F.LEG_SCHD_DEP_LCL_TME,	F.LEG_SCHD_ARR_LCL_DTE,	F.LEG_SCHD_ARR_LCL_TME,	F.LEG_SCHD_ARR_LCL_TMS,
	F.LEG_ACTL_DEP_LCL_DTE,	F.LEG_ACTL_DEP_LCL_TME,	F.LEG_ACTL_DEP_LCL_TMS,	F.LEG_ACTL_ARR_LCL_DTE,
	F.LEG_ACTL_ARR_LCL_TME,	F.LEG_ACTL_ARR_LCL_TMS,	F.LEG_DEP_DELAY_IATA_CDE,	F.ACT_DLY_CODE,
	F.LEG_DEP_DELAY_SECD_CDE,	F.CNL_REASON_CDE,	F.CNL_TMS,	F.FUEL_UOM,	F.INPUT_UOM,	F.COST_INDEX_ECO_CRUISE,	F.INPUT_VOL,	F.ESTIMATED_ZFW,	F.PLAN_ZEROFUEL_WGHT_AMT,	F.ZFW_ACUTAL,
	F.PLN_BLOCK_FUEL_AMT,	F.PLN_AIR_TIME,	F.MIN_FUEL_AUX,	F.PLN_TDWN_FUEL,	F.PLN_BLOCK_FUEL,	F.MIN_FUEL,
	F.LEG_TAXI_OUT,	F.ALT_FUEL,	F.ALT_STN,	F.PLN_ARR_RUNWAY,	F.PLN_DEP_RUNWAY,	F.DISPATCHER_NAME,
	F.PLN_SDWN_FUEL_AMT,	F.FIT,	F.PILOT_NAME,	F.PILOT_IN_CMD_EMP_NO,	F.AVG_WIND_COMP,	F.PLN_TAXI_OUT_TIME,
	F.TAXI_OUT_FF,	F.ACTL_TAXI_OUT_TIME,	F.PLN_FUEL_BURN,	F.FUEL_ONB_DEP_AUX,	F.FUEL_ONB_DEP_AUX2,	F.PLN_BLOCK_CHECK,
	F.FUEL_ONB_DEP_LT_EST,	F.FUEL_ONB_DEP_GT_EST,	F.FUEL_ONB_STO_AUX,	F.FUEL_ONB_STO_AUX2,	F.FUEL_ONB_ARR_AUX,
	F.FUEL_ONB_ARR_AUX2,	F.FUEL_ONB_LND_AUX,	F.PLN_TDWN_FUEL_T,	F.PLN_TDWN_FUEL_P,	F.FUEL_ONB_LND_AUX2,	F.TAXI_IN_FF,
	F.ACTL_TAXI_IN_TIME,	F.EST_ONB_ARR,	F.PLN_BLOCK_FUEL_T,	F.PLN_BLOCK_FUEL_P,	F.MIN_FUEL_CHECK,	F.FUEL_ONB_STO_LT_EST,	F.FUEL_ONB_STO_GT_EST,	F.FUEL_ONB_STO_AUX3,	F.FUEL_ONB_DEP_AUX3,	F.FUEL_ONB_ARR_AUX3,
	F.ACTL_CALC_ONB_DEP,	F.ACTL_CALC_ONB_STO,	F.ACTL_CALC_ONB_LND,	F.ACTL_CALC_ONB_ARR,	F.FUEL_ONB_DEP,	F.FUEL_ONB_STO,
	F.FUEL_ONB_LND,	F.FUEL_ONB_ARR,	F.ACTL_FUEL_BURN,	F.ACTL_FUEL_BURN_CORR,	--F.DELTA_BURN,
	--F.DELTA_BURN_PCT,	F.FUEL_ONB_LND_AUX3,	F.FUEL_BURN_STO,	F.FUEL_BURN_LND,	F.ACARS_FUEL_BURN,	F.PLN_TAXI_IN_TIME,
	F.PLN_TDWN_FUEL_AUX,	F.TKG,	F.TKG_SAVINGS,	F.ATC_FUEL,	F.WXX_FUEL,	F.DEV_FUEL,	F.OPN_FUEL,	F.CTG_FUEL,	F.ACF_FLAG,	F.POSTDATE,	F.LOAD_DTE,	R.CARRIER_NME,
	R.IATA_CDE,	CAST((F.LEG_ACTL_ORIG || ''-'' || F.LEG_ACTL_DEST) AS CHAR(7)) AS CITY_PAIR,
	1 AS FLIGHTS,
	(SELECT MAX(O.LEG_DIST_AIR_AMT) FROM TERADATA_MIG.PEDW.LEG_FLOWN_OPER O --View created by joining pedw_db.leg_flown_oper & pedw_stg.FSUM_Alternates_MLD table

	  WHERE ((INFLIGHT_IND = ''N'') AND (O.LEG_ID = F.LEG_ID))) AS LEG_DIST_AIR_AMT,
	TIMESTAMP_NTZ_FROM_PARTS(F.LEG_SCHD_ARR_DTE::DATE, F.LEG_SCHD_ARR_TME::TIME) AS LEG_SCHD_ARR_TMS,
	TO_DATE(STARTDATE, ''YYYY-MM-DD'') as START_DATE,
	TO_DATE(ENDDATE, ''YYYY-MM-DD'') as END_DATE,
	CAST(COUNT(*) OVER (PARTITION BY F.LEG_ACTL_ORIG, F.LEG_ACTL_DEST) AS DECIMAL(20, 0))AS NUM_FLIGHTS,
	2.0000 * (F.FLIGHT_ORIG_LCL_DTE - START_DATE + 1.0000) / (END_DATE - START_DATE + 2.0000) as WEIGHT_PRIME,
	SUM(WEIGHT_PRIME) OVER (PARTITION BY F.LEG_ACTL_ORIG, F.LEG_ACTL_DEST) AS SUM_WEIGHTS_PRIME,
	EXTRACT(HOUR FROM F.LEG_ACTL_ARR_LCL_TMS) AS ACTL_ARR_INTERVAL_HOUR,
	EXTRACT(HOUR FROM F.LEG_SCHD_ARR_LCL_TMS) AS SCHD_ARR_INTERVAL_HOUR,
	EXTRACT(HOUR FROM F.LEG_SCHD_ARR_TME) AS SCHD_ARR_INTERVAL_HOUR_UTC
	FROM TERADATA_MIG.PEDW.VW_LEG_FUEL F    --View created from VW_LEG_FUEL
				
    LEFT OUTER JOIN TERADATA_MIG.PEDW_SOC.REF_OPRN_FLIGHT_RANGE R ON (F.CARRIER_CDE = R.CARRIER_CDE) 
					AND (F.FLIGHT_NUM BETWEEN R.FLIGHT_RNG_STRT AND R.FLIGHT_RNG_END) 
					AND (F.FLIGHT_ORIG_LCL_DTE BETWEEN R.EFF_FROM_DTE AND R.EFF_TO_DTE)
    LEFT OUTER JOIN TERADATA_MIG.PEDW.LEG_FLOWN ON (F.LEG_ID = L.LEG_ID)
	
	WHERE (R.CARRIER_NME IN (''Air Canada'', ''Air Canada Rouge''))
		       AND (((L.LEG_DVRT_IND <> ''D'') OR (L.LEG_DVRT_IND IS NULL)) 
                             AND (R.OPRN_INCL_FLG = 1 or r.FLIGHT_RMRK like any (''%Cargo%'', ''%Charters%'')))
		       AND (F.FLIGHT_ORIG_LCL_DTE BETWEEN START_DATE AND END_DATE)) FlightDetails

	WHERE (NUM_FLIGHTS >= 30)) Computed_Fields
		
WHERE (OUTLIER_CHECK = 1)) Final_Table
ORDER BY 	CITY_PAIR,FLIGHT_ORIG_LCL_DTE				;
