
--Function Name -> FN_OPS0058_PAWOBS_SUMMARY_REPORT_SITA
CREATE OR REPLACE FUNCTION BI_REPORTSDB_REH.BI_REPORTS_OPS.FN_OPS0058_PAWOBS_SUMMARY_REPORT_SITA
                                                                   ("P_START_DATE" VARCHAR, "P_END_DATE" VARCHAR)
RETURNS TABLE (
"10" NUMBER(37,0), 
"20" NUMBER(37,0), 
"21" NUMBER(37,0), 
"26" NUMBER(37,0), 
"30" NUMBER(37,0), 
"40" NUMBER(37,0), 
"50" NUMBER(37,0), 
"53" NUMBER(37,0), 
"54" NUMBER(37,0), 
"57" NUMBER(37,0), 
"60" NUMBER(37,0), 
"70" NUMBER(37,0), 
"77" NUMBER(37,0), 
"RL_ERROR" NUMBER(37,0), 
"PAX" NUMBER(38,0), 
"FILES" NUMBER(38,0), 
"RATIO" NUMBER(38,1), 
"TARGET" NUMBER(38,1), 
"NEW_FIELD" VARCHAR(12), 
"LVL" NUMBER(2,0), 
"ORDERX" VARCHAR(16777216), 
"REGION_ORDER" NUMBER(8,2))
LANGUAGE SQL
AS 
WITH CTE_SITA_MASTER_REPORT AS (
			SELECT
				RL_10 + RL_20 + RL_30 + RL_40 + RL_50 + RL_60 + RL_70 AS FILES
				, DATE_FLIGHT AS DATE1
				, TO_CHAR(DATE_FLIGHT, ''YYYY-MM-DD'') AS DATE_FM
				, CASE
					WHEN REPORT_LEVEL_2 = ''Mainline Eastern Canada'' THEN ''AC Eastern''
					WHEN REPORT_LEVEL_2 = ''Mainline Western Canada'' THEN ''AC Western''
					WHEN REPORT_LEVEL_2 = ''Mainline USA'' THEN ''AC USA''
					WHEN REPORT_LEVEL_2 = ''Asia & Pacific'' THEN ''AC Asia''
					WHEN REPORT_LEVEL_2 = ''Europe Middle East & Africa'' THEN ''AC Europe''
					WHEN REPORT_LEVEL_2 = ''Latin America & Caribbean'' THEN ''AC Latin''
					WHEN REPORT_LEVEL_2 = ''Jazz Canada'' THEN ''QK Canada''
					WHEN REPORT_LEVEL_2 = ''Jazz USA'' THEN ''QK USA''
					WHEN REPORT_LEVEL_2 = ''Tier III'' THEN ''Tier III''
					ELSE NULL
				END AS REPOT_LVL
				, CASE
					WHEN REGION_LEVEL_3 = ''AIR CANADA NORTH AMERICA'' THEN ''NORTH AMERICA''
					WHEN REGION_LEVEL_3 = ''AIR CANADA INTERNATIONAL'' THEN ''INTERNATIONAL''
					WHEN REGION_LEVEL_3 = ''International'' THEN ''INTERNATIONAL''
					WHEN REGION_LEVEL_3 = ''REGIONAL'' THEN ''REGIONAL''
					ELSE NULL
				END AS MAIN_LVL
				, ''System'' AS SYSTEM
				, ''TOTAL SYSTEM'' AS NEW_FIELD_LVL0
				, 10 AS LVL0
				, ''Z'' AS ORDERX_LVL0
				, 99.0 AS REGION_ORDERX
				, MAIN_LVL AS NEW_FIELD_LVL1
				, 9 AS LVL1
				, ''Y'' AS ORDERX_LVL1
				, REPOT_LVL AS NEW_FIELD_LVL2
				, 02 AS LVL2
				, CASE 
					WHEN SORT_ORDER = 1 THEN ''A''
					WHEN SORT_ORDER = 2 THEN ''B''
					WHEN SORT_ORDER = 3 THEN ''C''
					WHEN SORT_ORDER = 4 THEN ''D''
					WHEN SORT_ORDER = 5 THEN ''E''
					WHEN SORT_ORDER = 6 THEN ''F''
					WHEN SORT_ORDER = 7 THEN ''G''
					WHEN SORT_ORDER = 8 THEN ''H''
					WHEN SORT_ORDER = 9 THEN ''I''
					WHEN SORT_ORDER = 10 THEN ''J''
					ELSE NULL
				END AS ORDERX_LVL2
				, STATION AS NEW_FIELD_LVL3
				, 03 AS LVL3
				, CASE 
					WHEN SORT_ORDER = 1 THEN ''A''
					WHEN SORT_ORDER = 2 THEN ''B''
					WHEN SORT_ORDER = 3 THEN ''C''
					WHEN SORT_ORDER = 4 THEN ''D''
					WHEN SORT_ORDER = 5 THEN ''E''
					WHEN SORT_ORDER = 6 THEN ''F''
					WHEN SORT_ORDER = 7 THEN ''G''
					WHEN SORT_ORDER = 8 THEN ''H''
					WHEN SORT_ORDER = 9 THEN ''I''
					WHEN SORT_ORDER = 10 THEN ''J''
					ELSE NULL
				END AS ORDERX_LVL3
				, RL_10
				, RL_20
				, RL_21
				, RL_26
				, RL_30
				, RL_40
				, RL_50
				, RL_53
				, RL_54
				, RL_57
				, RL_60
				, RL_70
				, RL_77
				, RL_ERROR
				, PAX
				, TARGET_FLAG
				, SYSTEM_TARGET
				, GLOBAL_TARGET
				, REGIONAL_TARGET
				, STATION_TARGET
				, REGION_ORDER
			FROM
				BI_REPORTS_OPS.TBL_PRST_CMN_SITA_MASTER_REPORT
			WHERE
				TARGET_FLAG = 1
					-- AND DATE_FLIGHT >= TO_CHAR(P_START_DT)
					-- AND DATE_FLIGHT <= TO_CHAR(P_END_DT)
                AND DATE_FLIGHT BETWEEN P_START_DATE AND P_END_DATE
		),
		-- LVL0 query to aggregate and compute values
		CTE_LVL0 AS (
			SELECT
				SUM(RL_10) AS "10"
				, SUM(RL_20) AS "20"
				, SUM(RL_21) AS "21"
				, SUM(RL_26) AS "26"
				, SUM(RL_30) AS "30"
				, SUM(RL_40) AS "40"
				, SUM(RL_50) AS "50"
				, SUM(RL_53) AS "53"
				, SUM(RL_54) AS "54"
				, SUM(RL_57) AS "57"
				, SUM(RL_60) AS "60"
				, SUM(RL_70) AS "70"
				, SUM(RL_77) AS "77"
				, SUM(RL_ERROR) AS RL_ERROR
				, SUM(PAX) AS PAX
				, SUM(FILES) AS FILES
				, ROUND(DIV0(SUM(FILES), SUM(PAX)) * 1000, 1) AS RATIO
				, ROUND(AVG(SYSTEM_TARGET), 1) AS TARGET
				, NEW_FIELD_LVL0 AS NEW_FIELD
				, LVL0 AS LVL
				, ORDERX_LVL0 AS ORDERX
				, REGION_ORDERX AS REGION_ORDER
			FROM
				CTE_SITA_MASTER_REPORT
			GROUP BY
				NEW_FIELD
				, LVL
				, ORDERX
				, REGION_ORDERX
		),
		-- LVL1 query to aggregate and compute values
		CTE_LVL1 AS (
			SELECT
				SUM(RL_10) AS "10"
				, SUM(RL_20) AS "20"
				, SUM(RL_21) AS "21"
				, SUM(RL_26) AS "26"
				, SUM(RL_30) AS "30"
				, SUM(RL_40) AS "40"
				, SUM(RL_50) AS "50"
				, SUM(RL_53) AS "53"
				, SUM(RL_54) AS "54"
				, SUM(RL_57) AS "57"
				, SUM(RL_60) AS "60"
				, SUM(RL_70) AS "70"
				, SUM(RL_77) AS "77"
				, SUM(RL_ERROR) AS RL_ERROR
				, SUM(PAX) AS PAX
				, SUM(FILES) AS FILES
				, ROUND(DIV0(SUM(FILES), SUM(PAX)) * 1000, 1) AS RATIO
				, ROUND(AVG(GLOBAL_TARGET), 1) AS TARGET
				, NEW_FIELD_LVL1 AS NEW_FIELD
				, LVL1 AS LVL
				, ORDERX_LVL1 AS ORDERX
				, REGION_ORDER
			FROM
				CTE_SITA_MASTER_REPORT
			GROUP BY
				NEW_FIELD
				, LVL
				, ORDERX
				, REGION_ORDER
		),
		-- LVL2 query to aggregate and compute values
		CTE_LVL2 AS (
			SELECT
				SUM(RL_10) AS "10"
				, SUM(RL_20) AS "20"
				, SUM(RL_21) AS "21"
				, SUM(RL_26) AS "26"
				, SUM(RL_30) AS "30"
				, SUM(RL_40) AS "40"
				, SUM(RL_50) AS "50"
				, SUM(RL_53) AS "53"
				, SUM(RL_54) AS "54"
				, SUM(RL_57) AS "57"
				, SUM(RL_60) AS "60"
				, SUM(RL_70) AS "70"
				, SUM(RL_77) AS "77"
				, SUM(RL_ERROR) AS RL_ERROR
				, SUM(PAX) AS PAX
				, SUM(FILES) AS FILES
				, ROUND(DIV0(SUM(FILES), SUM(PAX)) * 1000, 1) AS RATIO
				, ROUND(AVG(REGIONAL_TARGET), 1) AS TARGET
				, NEW_FIELD_LVL2 AS NEW_FIELD
				, LVL2 AS LVL
				, ORDERX_LVL2 AS ORDERX
				, REGION_ORDER
			FROM
				CTE_SITA_MASTER_REPORT
			GROUP BY
				NEW_FIELD
				, LVL
				, ORDERX
				, REGION_ORDER
		),
		-- LVL3 query to aggregate and compute values
		CTE_LVL3 AS (
			SELECT
				SUM(RL_10) AS "10"
				, SUM(RL_20) AS "20"
				, SUM(RL_21) AS "21"
				, SUM(RL_26) AS "26"
				, SUM(RL_30) AS "30"
				, SUM(RL_40) AS "40"
				, SUM(RL_50) AS "50"
				, SUM(RL_53) AS "53"
				, SUM(RL_54) AS "54"
				, SUM(RL_57) AS "57"
				, SUM(RL_60) AS "60"
				, SUM(RL_70) AS "70"
				, SUM(RL_77) AS "77"
				, SUM(RL_ERROR) AS RL_ERROR
				, SUM(PAX) AS PAX
				, SUM(FILES) AS FILES
				, ROUND(DIV0(SUM(FILES), SUM(PAX)) * 1000, 1) AS RATIO
				, ROUND(AVG(STATION_TARGET), 1) AS TARGET
				, NEW_FIELD_LVL3 AS NEW_FIELD
				, LVL3 AS LVL
				, ORDERX_LVL3 AS ORDERX
				, REGION_ORDER
			FROM
				CTE_SITA_MASTER_REPORT
			GROUP BY
				NEW_FIELD
				, LVL
				, ORDERX
				, REGION_ORDER
		),
		-- Union query to combine all data
		CTE_UNION AS (
			SELECT * FROM CTE_LVL0
			UNION
			SELECT * FROM CTE_LVL1
			UNION
			SELECT * FROM CTE_LVL2
			UNION
			SELECT * FROM CTE_LVL3
		)
		-- Summarize all combined data
		SELECT
			SUM("10") AS "10"
			, SUM("20") AS "20"
			, SUM("21") AS "21"
			, SUM("26") AS "26"
			, SUM("30") AS "30"
			, SUM("40") AS "40"
			, SUM("50") AS "50"
			, SUM("53") AS "53"
			, SUM("54") AS "54"
			, SUM("57") AS "57"
			, SUM("60") AS "60"
			, SUM("70") AS "70"
			, SUM("77") AS "77"
			, SUM(RL_ERROR) AS RL_ERROR
			, SUM(PAX) AS PAX
			, SUM(FILES) AS FILES
			, SUM(RATIO) AS RATIO
			, SUM(TARGET) AS TARGET
			, NEW_FIELD
			, LVL
			, ORDERX
			, REGION_ORDER
		FROM
			CTE_UNION
		GROUP BY
			NEW_FIELD
			, LVL
			, ORDERX
			, REGION_ORDER
		ORDER BY
			NEW_FIELD
			, LVL
			, ORDERX
			, REGION_ORDER;

-- BI_REPORTSDB_REH.BI_REPORTS_OPS.TBL_PRST_CMN_SITA_MASTER_REPORT Table
create or replace TABLE BI_REPORTSDB_REH.BI_REPORTS_OPS.TBL_PRST_CMN_SITA_MASTER_REPORT (
	DATE_YEAR NUMBER(4,0),
	DATE_MONTH NUMBER(2,0),
	DATE_FLIGHT DATE,
	STATION VARCHAR(3),
	PAX NUMBER(38,0),
	CODED_FILES NUMBER(13,0),
	RL_10 NUMBER(13,0),
	ERROR_10 NUMBER(13,0),
	RL_12 NUMBER(13,0),
	RL_16 NUMBER(13,0),
	RL_20 NUMBER(13,0),
	ERROR_20 NUMBER(13,0),
	RL_21 NUMBER(13,0),
	RL_22 NUMBER(13,0),
	RL_26 NUMBER(13,0),
	RL_30 NUMBER(13,0),
	ERROR_30 NUMBER(13,0),
	RL_31 NUMBER(13,0),
	RL_32 NUMBER(13,0),
	RL_40 NUMBER(13,0),
	ERROR_40 NUMBER(13,0),
	RL_41 NUMBER(13,0),
	RL_49 NUMBER(13,0),
	RL_50 NUMBER(13,0),
	ERROR_50 NUMBER(13,0),
	RL_53 NUMBER(13,0),
	RL_54 NUMBER(13,0),
	RL_56 NUMBER(13,0),
	RL_57 NUMBER(13,0),
	RL_60 NUMBER(13,0),
	ERROR_60 NUMBER(13,0),
	RL_62 NUMBER(13,0),
	RL_63 NUMBER(13,0),
	RL_65 NUMBER(13,0),
	RL_66 NUMBER(13,0),
	RL_67 NUMBER(13,0),
	RL_70 NUMBER(13,0),
	ERROR_70 NUMBER(13,0),
	RL_72 NUMBER(13,0),
	RL_73 NUMBER(13,0),
	RL_74 NUMBER(13,0),
	RL_76 NUMBER(13,0),
	RL_77 NUMBER(13,0),
	RL_ERROR NUMBER(13,0),
	STATION_TARGET NUMBER(19,9),
	REGIONAL_TARGET NUMBER(19,9),
	GLOBAL_TARGET NUMBER(19,9),
	SYSTEM_TARGET NUMBER(19,9),
	TARGET_FILES NUMBER(19,9),
	BUDGETED_PAX NUMBER(19,9),
	REPORT_LEVEL_2 VARCHAR(100),
	SORT_ORDER NUMBER(8,2),
	REGION_LEVEL_3 VARCHAR(100),
	REGION_ORDER NUMBER(8,2),
	TARGET_FLAG NUMBER(1,0),
	DATETIME_FLIGHT TIMESTAMP_NTZ(9),
	FLIGHT_DAY NUMBER(2,0),
	PAWOB_RATIO NUMBER(24,1)
);