

--Function1 -> FN_OPS0075_DISRUPTION_CODE_BREAKDOWN_REPORT3_APPR_ARRIVAL_DELAYS_FINAL
CREATE OR REPLACE FUNCTION BI_REPORTSDB_REH.BI_REPORTS_OPS.FN_OPS0075_DISRUPTION_CODE_BREAKDOWN_REPORT3_APPR_ARRIVAL_DELAYS_FINAL
                                                              ("P_FREQUENCY" VARCHAR(16777216), "P_AS_OF_DATE" VARCHAR(16777216))
RETURNS TABLE (
"APPR_SORT" NUMBER(38,0), 
"APPR_CATEGORY" VARCHAR(16777216), 
"PHL2_NAME" VARCHAR(16777216), 
"CARRIER_NME" VARCHAR(16777216), 
"FLIGHTS" NUMBER(38,0), 
"FLIGHTS_D" NUMBER(38,0))
LANGUAGE SQL
AS 
WITH CTE_LEG_FLOWN AS (SELECT
			lf.*,
			dcm.IRROPS_CONTROL_STATUS,
			dcm.PHL2,
			CASE WHEN lf.ARR_DELAY_TT_14 = 0 THEN ''On Time''
			    WHEN dcm.IRROPS_CONTROL_STATUS IS NULL THEN ''Within Carrier Control''
			    WHEN dcm.IRROPS_CONTROL_STATUS = ''NATIONAL AVIATION SYSTEM (NAS)'' THEN ''National Aviation System (NAS)''
			   WHEN dcm.IRROPS_CONTROL_STATUS = ''OUTSIDE CARRIER CONTROL - OTHERS'' THEN ''Outside Carrier Control - Others''
					WHEN dcm.IRROPS_CONTROL_STATUS = ''SECURITY'' THEN ''Security''
					WHEN dcm.IRROPS_CONTROL_STATUS = ''UPLINE'' THEN ''Upline''
					WHEN dcm.IRROPS_CONTROL_STATUS = ''WEATHER'' THEN ''Weather''
					WHEN dcm.IRROPS_CONTROL_STATUS = ''WITHIN CARRIER CONTROL'' THEN ''Within Carrier Control''
					WHEN dcm.IRROPS_CONTROL_STATUS = ''WITHIN CARRIER CONTROL - FOR SAFETY'' THEN ''Within Carrier Control - for Safety''
					ELSE ''''
				END AS APPR_CATEGORY,
				CASE 
					WHEN lf.ARR_DELAY_TT_14 = 0 THEN 0
					WHEN dcm.IRROPS_CONTROL_STATUS IS NULL THEN 6
					WHEN dcm.IRROPS_CONTROL_STATUS = ''NATIONAL AVIATION SYSTEM (NAS)'' THEN 1
					WHEN dcm.IRROPS_CONTROL_STATUS = ''OUTSIDE CARRIER CONTROL - OTHERS'' THEN 2
					WHEN dcm.IRROPS_CONTROL_STATUS = ''SECURITY'' THEN 3
					WHEN dcm.IRROPS_CONTROL_STATUS = ''UPLINE'' THEN 4
					WHEN dcm.IRROPS_CONTROL_STATUS = ''WEATHER'' THEN 5
					WHEN dcm.IRROPS_CONTROL_STATUS = ''WITHIN CARRIER CONTROL'' THEN 6
					WHEN dcm.IRROPS_CONTROL_STATUS = ''WITHIN CARRIER CONTROL - FOR SAFETY'' THEN 7
					ELSE -1
				END AS APPR_SORT,
				CASE 
					WHEN lf.ARR_DELAY_TT_14 = 0 THEN ''''
					ELSE dcm.PHL2
				END AS PHL2_NAME,
				CASE 
					WHEN lf.CARRIER_NME IN (''Air Canada Jazz'', ''PAL Airlines'') THEN ''Air Canada Express''
					ELSE lf.CARRIER_NME
				END AS CARRIER_NME_GROUP
			FROM BI_REPORTSDB_REH.BI_REPORTS_OPS.TBL_PRST_CMN_LEG_FLOWN lf
			LEFT JOIN TERADATA_MIG.PEDW_SOC.DELAY_CODE_MASTER dcm
				ON lf.ARR_DELAY_CDE_PRMY = dcm.DELAY_CODE_IATA_NETLINE
				AND lf.FLIGHT_ORIG_LCL_DTE BETWEEN dcm.EFFECTIVE_START_DT AND dcm.EFFECTIVE_END_DT
	),

CTE_INCLUDE_COMMON_DATES AS (
			SELECT
CASE
WHEN P_FREQUENCY = ''weekly''
THEN C.LW_BDT 
WHEN P_FREQUENCY = ''monthly''
THEN C.LM_BDT
WHEN P_FREQUENCY = ''yearly''
THEN C.LY_BDT
ELSE
''N/A''
END AS START_DT
, CASE
WHEN P_FREQUENCY = ''weekly''
THEN C.LW_EDT 
WHEN P_FREQUENCY = ''monthly''
THEN C.LM_EDT
WHEN P_FREQUENCY = ''yearly''
THEN C.LY_EDT
ELSE
''N/A''
END AS END_DT
				, F.APPR_SORT
				, F.APPR_CATEGORY
				, F.PHL2_NAME
				, F.CARRIER_NME_GROUP AS CARRIER_NME
, F.FLIGHTS
, F.CARRIER_CDE
, F.OTP_INCLUDE_FLAG
, FLIGHT_ORIG_LCL_DTE
			FROM
				CTE_LEG_FLOWN F
					CROSS JOIN TABLE (BI_REPORTSDB_REH.BI_REPORTS_CMN.fn_common_dates(P_AS_OF_DATE)) C
),
CTE_APPR_ARRIVAL_DELAYS_CARRIER AS (
	SELECT 
		APPR_SORT
		, APPR_CATEGORY
		, PHL2_NAME
		, CARRIER_NME
		, SUM(FLIGHTS) AS FLIGHTS
		, SUM(FLIGHTS) AS FLIGHTS_D
	FROM CTE_INCLUDE_COMMON_DATES
	WHERE CARRIER_CDE IN (''AC'', ''QK'', ''ZX'', ''RV'', ''PB'')
	 AND OTP_INCLUDE_FLAG = 1
	 AND FLIGHT_ORIG_LCL_DTE BETWEEN TO_DATE(START_DT) AND TO_DATE(END_DT)
	GROUP BY 
APPR_SORT
, APPR_CATEGORY
, PHL2_NAME
, CARRIER_NME
),
	CTE_APPR_ARRIVAL_DELAYS_SYSTEM AS (
		SELECT 
			APPR_SORT
			, APPR_CATEGORY
			, PHL2_NAME
			, ''SYSTEM'' AS CARRIER_NME
			, SUM(FLIGHTS_D) AS FLIGHTS_D
			, SUM(FLIGHTS) AS FLIGHTS
		FROM CTE_APPR_ARRIVAL_DELAYS_CARRIER
		GROUP BY 
			APPR_SORT
			, APPR_CATEGORY
			, PHL2_NAME
	)
	SELECT
		-- Grouping fields
		APPR_SORT
		, APPR_CATEGORY
		, PHL2_NAME
		, CARRIER_NME		
		-- Aggregate fields
		, SUM(FLIGHTS) AS FLIGHTS
		, SUM(FLIGHTS_D) AS FLIGHTS_D
	FROM (
		-- First data source
		SELECT 
			APPR_SORT
			, APPR_CATEGORY
			, PHL2_NAME
			, CARRIER_NME
			, FLIGHTS
			, FLIGHTS_D
		FROM CTE_APPR_ARRIVAL_DELAYS_CARRIER
		UNION ALL
		-- Second data source
		SELECT 
			APPR_SORT
			, APPR_CATEGORY
			, PHL2_NAME
			, CARRIER_NME
			, FLIGHTS
			, FLIGHTS_D
		FROM CTE_APPR_ARRIVAL_DELAYS_SYSTEM
	)
	GROUP BY 
		APPR_SORT, 
		APPR_CATEGORY, 
		PHL2_NAME, 
		CARRIER_NME
;

-- Function2 -> FN_OPS0075_DISRUPTION_CODE_BREAKDOWN_REPORT4_APPR_COMBINED_FINAL
CREATE OR REPLACE FUNCTION BI_REPORTSDB_REH.BI_REPORTS_OPS.FN_OPS0075_DISRUPTION_CODE_BREAKDOWN_REPORT4_APPR_COMBINED_FINAL
                                                                         ("P_FREQUENCY" VARCHAR(16777216), "P_AS_OF_DATE" VARCHAR(16777216))
RETURNS TABLE (
"APPR_SORT" NUMBER(38,0), 
"APPR_CATEGORY" VARCHAR(16777216), 
"CANCEL_REASON_CODE_NETLINE" VARCHAR(16777216), 
"CARRIER_NME" VARCHAR(16777216), 
"CNLS_D" NUMBER(38,0), 
"CNLS" NUMBER(38,0))
LANGUAGE SQL
AS 	
	WITH CTE_LEG_FLOWN AS (
			SELECT
				*
				, FLIGHTS AS CNLS
				, FLIGHTS AS CNLS_D
				, ''Operated Flights'' AS APPR_CATEGORY
				, 1 AS APPR_SORT
				, '''' AS CANCEL_REASON_CODE_NETLINE
				, CASE 
					WHEN CARRIER_NME IN (''Air Canada Jazz'', ''PAL Airlines'') THEN ''Air Canada Express''
					ELSE CARRIER_NME
				END AS CARRIER_NME_GROUP
			FROM BI_REPORTSDB_REH.BI_REPORTS_OPS.TBL_PRST_CMN_LEG_FLOWN
	),
	CTE_INCLUDE_COMMON_DATES AS (
			SELECT
                CASE
                    WHEN P_FREQUENCY = ''weekly''
                        THEN C.LW_BDT                          
                    WHEN P_FREQUENCY = ''monthly''
                        THEN C.LM_BDT
                    WHEN P_FREQUENCY = ''yearly''
                        THEN C.LY_BDT
                    ELSE
                        ''N/A''
                END AS START_DT
                , CASE
                    WHEN P_FREQUENCY = ''weekly''
                        THEN C.LW_EDT                          
                    WHEN P_FREQUENCY = ''monthly''
                        THEN C.LM_EDT
                    WHEN P_FREQUENCY = ''yearly''
                        THEN C.LY_EDT
                    ELSE
                        ''N/A''
                END AS END_DT
				, F.APPR_SORT
				, F.APPR_CATEGORY
				, F.CARRIER_NME_GROUP AS CARRIER_NME
                , F.CNLS_D
				, F.CNLS
                , F.CARRIER_CDE
                , F.OTP_INCLUDE_FLAG
                , FLIGHT_ORIG_LCL_DTE
				, CANCEL_REASON_CODE_NETLINE
			FROM
				CTE_LEG_FLOWN F
					CROSS JOIN TABLE (BI_REPORTSDB_REH.BI_REPORTS_CMN.fn_common_dates(P_AS_OF_DATE)) C
    ),
	CTE_APPR_FLOWN_CARRIER AS (
			SELECT
				APPR_CATEGORY
				, APPR_SORT
				, CANCEL_REASON_CODE_NETLINE
				, CARRIER_NME
				, SUM(CNLS_D) AS CNLS_D
				, SUM(CNLS) AS CNLS
			FROM CTE_INCLUDE_COMMON_DATES
			WHERE 
				CARRIER_CDE IN (''AC'', ''QK'', ''ZX'', ''RV'', ''PB'')
				AND OTP_INCLUDE_FLAG = 1
				AND FLIGHT_ORIG_LCL_DTE BETWEEN TO_DATE(START_DT) AND TO_DATE(END_DT)
			GROUP BY
				APPR_CATEGORY
				, APPR_SORT
				, CANCEL_REASON_CODE_NETLINE
				, CARRIER_NME
	),
	CTE_LEG_INCIDENT AS (
			SELECT
				*
				, TO_TIMESTAMP(CONCAT(TO_CHAR(TO_DATE(POSTDATE), ''YYYY-MM-DD''), '' '', TO_CHAR(TO_TIME(POSTTIME), ''HH24:MI:SS''))) AS TRANS_TMS
				, CASE
					WHEN CANCEL_REASON_CODE_NETLINE IN (''COMM'', ''POLI'', ''RTNS'') 
						THEN 0 
					ELSE LEG_CNL_COUNT 
				END AS EXCLUSIONS_PRE
				, CASE 
					WHEN DATEADD(HOUR, 48, TRANS_TMS) >= LEG_SCHD_DEP_TMS THEN 
						CASE 
							WHEN CANCEL_REASON_CODE_NETLINE = ''COMM'' THEN 0 
							ELSE LEG_CNL_COUNT 
						END
					ELSE 0 
				END AS EXCLUSIONS_POST
				, CASE 
					WHEN FLIGHT_ORIG_LCL_DTE >= ''2022-08-01'' THEN EXCLUSIONS_POST 
					ELSE EXCLUSIONS_PRE 
				END AS CNLS
				, CNLS AS CNLS_D
				, CASE 
					WHEN CANCEL_REASON_CODE_NETLINE IN (''AIRS'', ''ARPT'', ''RUNW'') THEN ''National Aviation System (NAS)''
					WHEN CANCEL_REASON_CODE_NETLINE IN (''POLI'', ''INDU'') THEN ''Outside Carrier Control - Others''
					WHEN CANCEL_REASON_CODE_NETLINE = ''WEAT'' THEN ''Weather''
					WHEN CANCEL_REASON_CODE_NETLINE IN (''COMM'', ''HOLI'', ''OPER'', ''POSI'', ''REPO'', ''RTNS'', ''EQUI'', ''FUEL'', ''HDLG'', ''ROTA'', ''CREW'') THEN ''Within Carrier Control''
					WHEN CANCEL_REASON_CODE_NETLINE IN (''DAMA'', ''PERF'', ''TECH'') THEN ''Within Carrier Control - for Safety''
					ELSE '''' 
				END AS APPR_CATEGORY
				, CASE 
					WHEN CANCEL_REASON_CODE_NETLINE IN (''AIRS'', ''ARPT'', ''RUNW'') THEN 2
					WHEN CANCEL_REASON_CODE_NETLINE IN (''POLI'', ''INDU'') THEN 3
					WHEN CANCEL_REASON_CODE_NETLINE = ''WEAT'' THEN 4
					WHEN CANCEL_REASON_CODE_NETLINE IN (''COMM'', ''HOLI'', ''OPER'', ''POSI'', ''REPO'', ''RTNS'', ''EQUI'', ''FUEL'', ''HDLG'', ''ROTA'', ''CREW'') THEN 5
					WHEN CANCEL_REASON_CODE_NETLINE IN (''DAMA'', ''PERF'', ''TECH'') THEN 6
					ELSE -1 
				END AS APPR_SORT
				, CASE 
					WHEN CARRIER_NME IN (''Air Canada Jazz'', ''PAL Airlines'') THEN ''Air Canada Express'' 
					ELSE CARRIER_NME 
				END AS CARRIER_NME_GROUP
				, CASE 
					WHEN CANCEL_REASON_CODE_NETLINE = '''' THEN ''Uncoded'' 
					ELSE CANCEL_REASON_CODE_NETLINE 
				END AS CANCEL_REASON_CODE_NETLINE_1
			FROM BI_REPORTSDB_REH.BI_REPORTS_OPS.VW_CMN_LEG_INCIDENT
	),
	CTE_INCLUDE_COMMON_DATES_1 AS (
			SELECT
                CASE
                    WHEN P_FREQUENCY = ''weekly''
                        THEN C.LW_BDT                          
                    WHEN P_FREQUENCY = ''monthly''
                        THEN C.LM_BDT
                    WHEN P_FREQUENCY = ''yearly''
                        THEN C.LY_BDT
                    ELSE
                        ''N/A''
                END AS START_DT
                , CASE
                    WHEN P_FREQUENCY = ''weekly''
                        THEN C.LW_EDT                          
                    WHEN P_FREQUENCY = ''monthly''
                        THEN C.LM_EDT
                    WHEN P_FREQUENCY = ''yearly''
                        THEN C.LY_EDT
                    ELSE
                        ''N/A''
                END AS END_DT
				, F.APPR_SORT
				, F.APPR_CATEGORY
				, F.CARRIER_NME_GROUP AS CARRIER_NME
                , F.CNLS_D
				, F.CNLS
                , F.CARRIER_CDE
                , F.OPRN_RNG_FLAG
                , F.FLIGHT_ORIG_LCL_DTE
				, F.CANCEL_REASON_CODE_NETLINE_1 AS CANCEL_REASON_CODE_NETLINE
			FROM
				CTE_LEG_INCIDENT F
					CROSS JOIN TABLE (BI_REPORTSDB_REH.BI_REPORTS_CMN.fn_common_dates(P_AS_OF_DATE)) C
                    -- CROSS JOIN TABLE (BI_REPORTSDB_REH.BI_REPORTS_CMN.fn_common_dates(''20220516'')) C
	),
	CTE_APPR_CNLS_CARRIER AS (
			SELECT
				APPR_SORT
				, APPR_CATEGORY
				, CANCEL_REASON_CODE_NETLINE
				, CARRIER_NME
				, SUM(CNLS_D) AS CNLS_D
				, SUM(CNLS) AS CNLS
			FROM
				CTE_INCLUDE_COMMON_DATES_1
			WHERE CARRIER_CDE IN (''AC'', ''QK'', ''ZX'', ''RV'', ''PB'')
			AND FLIGHT_ORIG_LCL_DTE BETWEEN TO_DATE(START_DT) AND TO_DATE(END_DT)
            AND OPRN_RNG_FLAG = 1
			GROUP BY
				APPR_SORT
				, APPR_CATEGORY
				, CANCEL_REASON_CODE_NETLINE
				, CARRIER_NME
	),
	CTE_APPR_COMBINED_CARRIER AS (
			SELECT
				APPR_SORT
				, APPR_CATEGORY
				, CANCEL_REASON_CODE_NETLINE
				, CARRIER_NME
				, SUM(CNLS_D) AS CNLS_D
				, SUM(CNLS) AS CNLS
			FROM (
			-- First data source
					SELECT 
						APPR_SORT
						, APPR_CATEGORY
						, CANCEL_REASON_CODE_NETLINE
						, CARRIER_NME
						, CNLS_D
						, CNLS
					FROM CTE_APPR_FLOWN_CARRIER
					UNION ALL
			-- Second data source
					SELECT 
						APPR_SORT
						, APPR_CATEGORY
						, CANCEL_REASON_CODE_NETLINE
						, CARRIER_NME
						, CNLS_D
						, CNLS
					FROM CTE_APPR_CNLS_CARRIER
				)
				GROUP BY 
					APPR_SORT 
					, APPR_CATEGORY 
					, CANCEL_REASON_CODE_NETLINE
					, CARRIER_NME
	),
	CTE_APPR_COMBINED_SYSTEM AS (
		SELECT			
			APPR_SORT
			, APPR_CATEGORY
			, CANCEL_REASON_CODE_NETLINE
			, ''SYSTEM'' AS CARRIER_NME
			, SUM(CNLS_D) AS CNLS_D
			, SUM(CNLS) AS CNLS
		FROM CTE_APPR_COMBINED_CARRIER
		GROUP BY
			APPR_SORT
			, APPR_CATEGORY
			, CANCEL_REASON_CODE_NETLINE
	)
	SELECT
		-- Grouping fields
		APPR_SORT
		, APPR_CATEGORY
		, CANCEL_REASON_CODE_NETLINE
		, CARRIER_NME
		-- Aggregate fields
		, SUM(CNLS_D) AS CNLS_D
		, SUM(CNLS) AS CNLS
	FROM (
		-- First data source
		SELECT 
			APPR_SORT
			, APPR_CATEGORY
			, CANCEL_REASON_CODE_NETLINE
			, CARRIER_NME
			, CNLS_D
			, CNLS
		FROM CTE_APPR_COMBINED_CARRIER
		UNION ALL
		-- Second data source
		SELECT 
			APPR_SORT
			, APPR_CATEGORY
			, CANCEL_REASON_CODE_NETLINE
			, CARRIER_NME
			, CNLS_D
			, CNLS
		FROM CTE_APPR_COMBINED_SYSTEM
	)
	GROUP BY 
		APPR_SORT
		, APPR_CATEGORY 
		, CANCEL_REASON_CODE_NETLINE 
		, CARRIER_NME;
